---
- name: OS | ntp | Stop if we dont have the required variables
  fail:
    msg: Computer says no. This role needs 'ntp_servers' var to be set.
  when: ntp_servers is undefined
  tags:
  - os
  - ntp

- name: OS | ntp | Install NTP Package
  yum:
    name: ntp
    state: installed
  notify: enable ntpd
  tags:
  - os
  - ntp

- name: OS | ntp | Install ntp.conf
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0640
  notify: restart ntpd
  tags:
  - os
  - ntp

